### ISSUE TITLE
Bad symbolic reference

### ISSUE THREAD

**Issue by tarushbali** [Rhinofly/play-s3#41]
I am getting the following error:

bad symbolic reference to fly.play.aws encountered in class file 'S3.class'.
Cannot access term aws in package fly.play. The current classpath may be
missing a definition for fly.play.aws, or S3.class may have been compiled against a version that's
incompatible with the one found on the current classpath.

I am just trying to get a bucket:

    val bucket = S3("bucketA")

Any idea why this might be happening? 

My conf file has my access key and my private key.

**Comment by EECOLOR** [comment]
If you still have this problem, please answer the questions and reopen the issue
