### ISSUE TITLE
Can't specify timeout

### ISSUE THREAD

**Issue by slorber** [Rhinofly/play-s3#44]
Hi

It seems the only way to add a different timeout is by changing global play WS config (ws.timeout). It should be possible to configure a specific timeout for uploads since uploads usually take longer than other request.

**Comment by EECOLOR** [comment]
Checkout https://github.com/Rhinofly/play-s3/tree/6.0.0, it's available as `6.0.0-RC1`. It should provide another way to deal with this. If it solves your problem let me know, same for any other problems.
