### ISSUE TITLE
Possible Bug On Malformed URL

### ISSUE THREAD

**Issue by neilchaudhuri** [Rhinofly/play-s3#46]
When I do the following:

bucket.get("some.bad.url")

I get the following immediately:

java.lang.IllegalArgumentException: Illegal character in path at index 174
at java.net.URI.create(URI.java:859)
at fly.play.aws.auth.Request.uri$lzycompute(Request.scala:13)
...

The exception is fine of course, but shouldn't it be wrapped in a Failure within the Future to be unlocked with a recover rather than just happen synchronously? Or am I just doing something dumb?

Thanks.

**Comment by EECOLOR** [comment]
I agree, that would simplify recovery for dynamic usage. This would however break backwards compatibility, so I will add it on the next big version bump.

**Comment by EECOLOR** [comment]
Thinking about that, it's quite tricky. The error happens quite far away from the method call. I am wondering what the benefit would be of catching it into a future failure.

Maybe it helps to know your usecase. For most people this would just be a programming error, for which it's fine to have an early exception with a clear origin. Could you explain your usecase a bit more?

**Comment by neilchaudhuri** [comment]
My use case isn't terribly elaborate. I was simply using the method normally and assumed all errors would be in Futures and coded accordingly. The fact this one wasn't led to weirdness on my end until I figured out the issue.

So it was my bad for assuming.

If it is too much trouble, then I guess simply documenting which exceptions are synchronous and which are asynchronous should be sufficient.

**Comment by EECOLOR** [comment]
The problem with that is that errors as the one in this particular example come from Java.

**Comment by EECOLOR** [comment]
I am closing this issue as a 'wont fix'. There are too many potential exceptions that can be thrown.

**Comment by neilchaudhuri** [comment]
Just to be clear, I raised the issue not because I care about differentiating among exceptions but because I was hoping whatever exception happens can be recovered from the Future. I think handling exceptions from Java libraries is possible though I've never had to do it it. So easy for me to say.

But yeah, if that's too hard to do, then that's cool.

**Comment by EECOLOR** [comment]
In this case there should be no reason to catch it. It will be caught (at least I hope) on your first test run as it indicates an invalid url which you do not want to leave around.

If you are assigning the url dynamically (from a user form or something similar) then I hope you would validate the url before using using it. So even in this dynamic case the exception would not occur when the application is running in production.
